version: "3.9"

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-network:
    driver: bridge
